---
- hosts: undercloud
  gather_facts: False
  tasks:
  - name: Print Perfomance Result to CSV
    shell: |
      cat {{ '/tmp/performance.log' }} |grep -B14 "Finished binary-search"|awk 'BEGIN {print "Stream 0->1 Latency,Stream 1->0 Latency,Stream 0->1 Throughput,Stream 1->0 Throughput,Aggregate Throughput" }/Latency RX/ {if ($5=="0->1"){split($14,a,"=");str1=a[2]}} /Latency RX/ {if ($5=="1->0"){split($14,a,"=");str2=a[2]}} /TX rate tolerance/ {if ($11=="0"){split($21,a,")");str3=a[1]}} /TX rate tolerance/ {if ($11=="1"){split($21,a,")");str4=a[1]} } END {print str1","str2","str3","str4","str3+str4}' > /tmp/perf.csv
    args:
      executable: bash

  - name: Copy perf results file to localhost
    fetch:
      flat: yes
      src: "{{ item }}"
      dest: "./"
    with_items:
      - '/tmp/perf.csv'
